### ISSUE TITLE
Numpy incompatibility: ValueError: numpy.dtype size changed

### ISSUE THREAD

**Issue by robotrapta** [groundlight/framegrab#58]
I'm getting an error after `import framegrab` using the Groundlight RPI image:

```
>>> import framegrab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/groundlight/gl-py/lib/python3.11/site-packages/framegrab/__init__.py", line 3, in <module>
    from .grabber import FrameGrabber
  File "/opt/groundlight/gl-py/lib/python3.11/site-packages/framegrab/grabber.py", line 35, in <module>
    from picamera2 import Picamera2
  File "/usr/lib/python3/dist-packages/picamera2/__init__.py", line 9, in <module>
    from .picamera2 import Picamera2, Preview
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 27, in <module>
    from picamera2.encoders import Encoder, H264Encoder, MJPEGEncoder, Quality
  File "/usr/lib/python3/dist-packages/picamera2/encoders/__init__.py", line 6, in <module>
    from .jpeg_encoder import JpegEncoder
  File "/usr/lib/python3/dist-packages/picamera2/encoders/jpeg_encoder.py", line 3, in <module>
    import simplejpeg
  File "/usr/lib/python3/dist-packages/simplejpeg/__init__.py", line 1, in <module>
    from ._jpeg import encode_jpeg
  File "simplejpeg/_jpeg.pyx", line 1, in init simplejpeg._jpeg
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

python version is 3.11.2 on debian `Linux hwn24 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux`

Managing dependencies with poetry.  Attaching pyproject.toml and poetry.lock
[poetry.lock.txt](https://github.com/user-attachments/files/17267736/poetry.lock.txt)
[pyproject.toml.txt](https://github.com/user-attachments/files/17267737/pyproject.toml.txt)

**Comment by robotrapta** [comment]
Seems like this is an incompatibility with `numpy 2.0`.  So I worked around it with this line in the pyproject:

```
numpy = "^1.0"
```

**Comment by 2d2d1** [comment]
Numpy版本和Python版本的对应关系找准就好
